name: doc_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.7+1
  intl: ^0.19.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.2.0
  dio: ^5.8.0+1
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true
  android_12:
    image: assets/images/splash.png
    icon_background_color: "#ffffff"
